[build]
  builder = "DOCKERFILE"
  dockerfilePath = "packages/twenty-docker/twenty/Dockerfile"

[deploy]
  numReplicas = 1
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[[services]]
  name = "twenty-server"
  
[[services]]
  name = "twenty-worker"

[[services]]
  name = "postgres"
  
[[services]]
  name = "redis" 